### ISSUE TITLE
Unable to install digimend for huion 420 on arch

### ISSUE THREAD

**Issue by zeroeightysix** [DIGImend/digimend-kernel-drivers#159]
Hello,
I've tried installing digimend for my huion 420 on arch. First tried installing the package with little success, tried to clone, make & make install to get it working - no success. (All had reboots after).
When attempting to find what's going wrong I found some of the following information:
`grep -e "Using input driver " /var/log/Xorg.0.log`
would show that:
```
[  5098.001] (II) Using input driver 'libinput' for 'HUION 420 Pen'
[  5098.191] (II) Using input driver 'libinput' for 'HUION 420 Pad'
[  5098.303] (II) Using input driver 'libinput' for 'HUION 420 Mouse'
[  5098.428] (II) Using input driver 'libinput' for 'HUION 420 Keyboard'
[  5098.454] (II) Using input driver 'libinput' for 'HUION 420 Consumer Control'
[  5098.481] (II) Using input driver 'libinput' for 'HUION 420 System Control'
```
it's using libinput as driver for my tablet.
So, I tried editing the file `/etc/X11/xorg.conf.d/10-pen.conf` to contain this:
```
Section "InputDevice"
    Identifier "HUION 420 Consumer Control"
    Driver "digimend"
EndSection

Section "InputDevice"
    Identifier "HUION 420 Pen"
    Driver "digimend"
EndSection

Section "InputDevice"
    Identifier "HUION 420 Pad"
    Driver "digimend"
EndSection
```
with no success.

Then I found out:
`sudo libinput list-devices`
Shows that:
```
libinput error: event9  - HUION 420 Mouse: libinput bug: missing tablet capabilities: xy pen btn-stylus resolution. Ignoring this device.
libinput error: event10 - HUION 420 Keyboard: libinput bug: missing tablet capabilities: xy pen btn-stylus resolution. Ignoring this device.
libinput error: event12 - HUION 420 System Control: libinput bug: missing tablet capabilities: xy pen btn-stylus resolution. Ignoring this device.
```
Only the `Consumer Control`, `Pen` and `Tablet` appears to load correctly.

I'm clueless on how to act further. What am I doing wrong? Please help, Thank you in advance!

EDIT: Please note: the tablet absolutely works - but it's using its full area for mapping the cursor location. What I want to achieve is being able to modify the active area.

**Comment by spbnick** [comment]
@zeroeightysix, libinput is the next-level, user-space driver, using what the DIGImend drivers provide from kernel-space, and is normally handling the tablet on X.org these days. The `libinput error` you get is interesting, but I don't think it has any consequence. Those devices are essentially dummies, and we create them for compatibility, but I think we should stop doing that, as they only create confusion.

You can modify the active area with xinput coordinate transformation matrix. There might be some tools which can help you with that, as the math is somewhat hard to grasp.

Otherwise, since you're saying your tablet works, I'll close this issue. Reopen if you feel I shouldn't.
