### ISSUE TITLE
Huion Inspiroy 2 Support

### ISSUE THREAD

**Issue by jacobranson** [DIGImend/digimend-kernel-drivers#661]
I specifically have the 2 M. Unsure if there would be a separate effort for the large and small variants. Happy to help debug, or even throw a few bucks in to make this happen.

**Comment by raman-maker** [comment]
Are you able to use Huion Inspiroy 2 tablet ? 
is your problem solved ?

**Comment by jacobranson** [comment]
@raman-maker There hasn't been a commit on main in 7 months, so no.

**Comment by raman-maker** [comment]
HUION Inspiroy 2 tablet works on Manjaro Linux.  Use command below to install it :
`pamac build huiontablet`

https://forum.manjaro.org/t/huion-inspiroy-2-driver-installation-in-manjaro-linux/152049/1

**Comment by jacobranson** [comment]
Yeah but that's not part of the digimend kernel drivers. That's an out of tree driver that isn't open source. @raman-maker

**Comment by JoseExposito** [comment]
Hi!

Your issue should be fixed by [DIGImend v13](https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v13). Please, if you have a chance, give it a try and report any problems found.

This was the related pull request fixing it: https://github.com/DIGImend/digimend-kernel-drivers/pull/679
